export const CA = "0xc2DBBF2B08F31f53867E7E58398747a1D5170d84";

export const ABI = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "makersId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "targetCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "dDay",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "postId",
        type: "string",
      },
      { indexed: false, internalType: "string", name: "title", type: "string" },
    ],
    name: "MakersCreated",
    type: "event",
    signature:
      "0xe9dd14627f61a5658b1c89a6e51ea8ad5f452466b38ef9db823fe0a8ffdf75be",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "buyerMakers",
    outputs: [
      { internalType: "uint256", name: "makersId", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "targetCount", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "dDay", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x3cbe5e63",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "makersBuyers",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xf1ecd255",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "makersByMakersId",
    outputs: [
      { internalType: "uint256", name: "makersId", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "targetCount", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "dDay", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x44741e3a",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "makersByPostId",
    outputs: [
      { internalType: "uint256", name: "makersId", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "targetCount", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "dDay", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x4bbdf53d",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "makersState",
    outputs: [
      { internalType: "enum MakersContract.State", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xdd06c781",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "sellerMakers",
    outputs: [
      { internalType: "uint256", name: "makersId", type: "uint256" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "targetCount", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
      { internalType: "uint256", name: "dDay", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x5b511377",
  },
  {
    inputs: [
      { internalType: "string", name: "postId", type: "string" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "targetCount", type: "uint256" },
      { internalType: "uint256", name: "dDay", type: "uint256" },
    ],
    name: "createMakers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xc8326630",
  },
  {
    inputs: [],
    name: "getTotalMakers",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "makersId", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "targetCount", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "uint256", name: "dDay", type: "uint256" },
          { internalType: "uint256", name: "count", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "string", name: "postId", type: "string" },
          { internalType: "string", name: "title", type: "string" },
        ],
        internalType: "struct MakersContract.Makers[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xf7d7224d",
  },
  {
    inputs: [],
    name: "getSellerMakers",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "makersId", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "targetCount", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "uint256", name: "dDay", type: "uint256" },
          { internalType: "uint256", name: "count", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "string", name: "postId", type: "string" },
          { internalType: "string", name: "title", type: "string" },
        ],
        internalType: "struct MakersContract.Makers[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xdff75530",
  },
  {
    inputs: [],
    name: "getBuyerMakers",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "makersId", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "targetCount", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "uint256", name: "dDay", type: "uint256" },
          { internalType: "uint256", name: "count", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "string", name: "postId", type: "string" },
          { internalType: "string", name: "title", type: "string" },
        ],
        internalType: "struct MakersContract.Makers[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x08ce847b",
  },
  {
    inputs: [{ internalType: "uint256", name: "makersId", type: "uint256" }],
    name: "getMakersByMakersId",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "makersId", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "targetCount", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "uint256", name: "dDay", type: "uint256" },
          { internalType: "uint256", name: "count", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "string", name: "postId", type: "string" },
          { internalType: "string", name: "title", type: "string" },
        ],
        internalType: "struct MakersContract.Makers",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x68bafc9b",
  },
  {
    inputs: [{ internalType: "string", name: "postId", type: "string" }],
    name: "getMakersByPostId",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "makersId", type: "uint256" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "targetCount", type: "uint256" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
          { internalType: "uint256", name: "dDay", type: "uint256" },
          { internalType: "uint256", name: "count", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "string", name: "postId", type: "string" },
          { internalType: "string", name: "title", type: "string" },
        ],
        internalType: "struct MakersContract.Makers",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x0704884b",
  },
  {
    inputs: [{ internalType: "uint256", name: "makersId", type: "uint256" }],
    name: "getMakersBuyers",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xe4b54d07",
  },
  {
    inputs: [{ internalType: "uint256", name: "makersId", type: "uint256" }],
    name: "getMakersState",
    outputs: [
      { internalType: "enum MakersContract.State", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x687683e4",
  },
];
